### ISSUE TITLE
No module named 'examples.instrument'

### ISSUE THREAD

**Issue by ling-pan** [rail-berkeley/softlearning#117]
Hi, I followed the installation steps, by I am getting the error. I wonder whether you can provide any ideas about solving this issue?

`(softlearning) [softlearning]$ softlearning run_example_local examples.development     --universe=gym     --domain=HalfCheetah     --task=v3     --exp-name=my-sac-experiment-1     --checkpoint-frequency=1000
Traceback (most recent call last):
  File "/home/anaconda3/envs/softlearning/bin/softlearning", line 11, in <module>
    load_entry_point('softlearning', 'console_scripts', 'softlearning')()
  File "/home/anaconda3/envs/softlearning/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/anaconda3/envs/softlearning/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/home/anaconda3/envs/softlearning/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/anaconda3/envs/softlearning/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/softlearning/softlearning/scripts/console_scripts.py", line 26, in <module>
    from examples.instrument import (
ModuleNotFoundError: No module named 'examples.instrument'`

**Comment by Artemis-Skade** [comment]
I have the same problem (after creating and activating the conda environment and installing with pip install -e .). How did you resolve it?
