### ISSUE TITLE
base_policy to_yaml fails

### ISSUE THREAD

**Issue by kapsl** [rail-berkeley/softlearning#135]
When running no preprocessor, everything seems to work.

I created a preprocessor, that is almost the same as your convnet preprocessor. I cannot test your convnet preprocessor directly, because I have no image environment.

to_yaml gives following error message, but i have no idea, what the weakref object could be...

2020-04-06 13:59:29,554	ERROR trial_runner.py:538 -- Trial id=00000-seed=2976: Error processing result.
Traceback (most recent call last):
  File "/home/manuel/miniconda3/envs/softlearning_new/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 536, in _process_trial_save
    checkpoint_value = self.trial_executor.fetch_result(trial)
  File "/home/manuel/miniconda3/envs/softlearning_new/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 381, in fetch_result
    result = ray.get(trial_future[0], DEFAULT_GET_TIMEOUT)
  File "/home/manuel/miniconda3/envs/softlearning_new/lib/python3.7/site-packages/ray/worker.py", line 1513, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(TypeError): ray::ExperimentRunner.save() (pid=13928, ip=192.168.0.141)
  File "python/ray/_raylet.pyx", line 452, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 407, in ray._raylet.execute_task.function_executor
  File "/home/manuel/miniconda3/envs/softlearning_new/lib/python3.7/site-packages/ray/tune/trainable.py", line 342, in save
    checkpoint = self._save(checkpoint_dir)
  File "/home/manuel/Code/translearn/softlearning_new/examples/development/main.py", line 238, in _save
    self._save_policy(checkpoint_dir)
  File "/home/manuel/Code/translearn/softlearning_new/examples/development/main.py", line 180, in _save_policy
    self.policy.save(save_path)
  File "/home/manuel/Code/translearn/softlearning_new/softlearning/policies/base_policy.py", line 229, in save
    config_yaml = self.to_yaml()
  File "/home/manuel/Code/translearn/softlearning_new/softlearning/policies/base_policy.py", line 221, in to_yaml
    yaml.dump(self._updated_config(), **kwargs)
  File "/home/manuel/miniconda3/envs/softlearning_new/lib/python3.7/site-packages/yaml/__init__.py", line 290, in dump
    return dump_all([data], stream, Dumper=Dumper, **kwds)
  File "/home/manuel/miniconda3/envs/softlearning_new/lib/python3.7/site-packages/yaml/__init__.py", line 278, in dump_all
    dumper.represent(data)
  File "/home/manuel/miniconda3/envs/softlearning_new/lib/python3.7/site-packages/yaml/representer.py", line 27, in represent
    node = self.represent_data(data)
  File "/home/manuel/miniconda3/envs/softlearning_new/lib/python3.7/site-packages/yaml/representer.py", line 48, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/home/manuel/miniconda3/envs/softlearning_new/lib/python3.7/site-packages/yaml/representer.py", line 207, in represent_dict
    return self.represent_mapping('tag:yaml.org,2002:map', data)
  File "/home/manuel/miniconda3/envs/softlearning_new/lib/python3.7/site-packages/yaml/representer.py", line 118, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/home/manuel/miniconda3/envs/softlearning_new/lib/python3.7/site-packages/yaml/representer.py", line 48, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/home/manuel/miniconda3/envs/softlearning_new/lib/python3.7/site-packages/yaml/representer.py", line 207, in represent_dict
    return self.represent_mapping('tag:yaml.org,2002:map', data)
  File "/home/manuel/miniconda3/envs/softlearning_new/lib/python3.7/site-packages/yaml/representer.py", line 118, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/home/manuel/miniconda3/envs/softlearning_new/lib/python3.7/site-packages/yaml/representer.py", line 48, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/home/manuel/miniconda3/envs/softlearning_new/lib/python3.7/site-packages/yaml/representer.py", line 364, in represent_ordered_dict
    return self.represent_sequence(tag, [items])
  File "/home/manuel/miniconda3/envs/softlearning_new/lib/python3.7/site-packages/yaml/representer.py", line 92, in represent_sequence
    node_item = self.represent_data(item)
  File "/home/manuel/miniconda3/envs/softlearning_new/lib/python3.7/site-packages/yaml/representer.py", line 48, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/home/manuel/miniconda3/envs/softlearning_new/lib/python3.7/site-packages/yaml/representer.py", line 199, in represent_list
    return self.represent_sequence('tag:yaml.org,2002:seq', data)
  File "/home/manuel/miniconda3/envs/softlearning_new/lib/python3.7/site-packages/yaml/representer.py", line 92, in represent_sequence
    node_item = self.represent_data(item)
  File "/home/manuel/miniconda3/envs/softlearning_new/lib/python3.7/site-packages/yaml/representer.py", line 48, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/home/manuel/miniconda3/envs/softlearning_new/lib/python3.7/site-packages/yaml/representer.py", line 199, in represent_list
    return self.represent_sequence('tag:yaml.org,2002:seq', data)
  File "/home/manuel/miniconda3/envs/softlearning_new/lib/python3.7/site-packages/yaml/representer.py", line 92, in represent_sequence
    node_item = self.represent_data(item)
  File "/home/manuel/miniconda3/envs/softlearning_new/lib/python3.7/site-packages/yaml/representer.py", line 52, in represent_data
    node = self.yaml_multi_representers[data_type](self, data)
  File "/home/manuel/miniconda3/envs/softlearning_new/lib/python3.7/site-packages/yaml/representer.py", line 343, in represent_object
    'tag:yaml.org,2002:python/object:'+function_name, state)
  File "/home/manuel/miniconda3/envs/softlearning_new/lib/python3.7/site-packages/yaml/representer.py", line 118, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/home/manuel/miniconda3/envs/softlearning_new/lib/python3.7/site-packages/yaml/representer.py", line 52, in represent_data
    node = self.yaml_multi_representers[data_type](self, data)
  File "/home/manuel/miniconda3/envs/softlearning_new/lib/python3.7/site-packages/yaml/representer.py", line 343, in represent_object
    'tag:yaml.org,2002:python/object:'+function_name, state)
  File "/home/manuel/miniconda3/envs/softlearning_new/lib/python3.7/site-packages/yaml/representer.py", line 118, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/home/manuel/miniconda3/envs/softlearning_new/lib/python3.7/site-packages/yaml/representer.py", line 48, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/home/manuel/miniconda3/envs/softlearning_new/lib/python3.7/site-packages/yaml/representer.py", line 207, in represent_dict
    return self.represent_mapping('tag:yaml.org,2002:map', data)
  File "/home/manuel/miniconda3/envs/softlearning_new/lib/python3.7/site-packages/yaml/representer.py", line 117, in represent_mapping
    node_key = self.represent_data(item_key)
  File "/home/manuel/miniconda3/envs/softlearning_new/lib/python3.7/site-packages/yaml/representer.py", line 52, in represent_data
    node = self.yaml_multi_representers[data_type](self, data)
  File "/home/manuel/miniconda3/envs/softlearning_new/lib/python3.7/site-packages/yaml/representer.py", line 317, in represent_object
    reduce = data.__reduce_ex__(2)
TypeError: can't pickle weakref objects
2020-04-06 13:59:29,561	INFO trial_runner.py:636 -- Trial id=00000-seed=2976: Attempting to restore trial state from last checkpoint.

**Comment by hartikainen** [comment]
Hey @kapsl! I'll try to reproduce this on my end once I have time and will write some tests to make sure this works.

In the meanwhile, what would happen if you changed this line:
https://github.com/rail-berkeley/softlearning/blob/84d7589fd5852aff9aa46debda6de39acaec2e0b/softlearning/policies/base_policy.py#L201
to `'preprocessors': tree.map(preprocessors_lib.serialize, self._preprocessors),`?

**Comment by kapsl** [comment]
Then it seems to work :-)
