### ISSUE TITLE
No module named 'example.instruments'

### ISSUE THREAD

**Issue by Artemis-Skade** [rail-berkeley/softlearning#161]
Duplicate of #117 but no solution was provided, so I reopen it here.
Console dump:
```
softlearning run_example_local examples.development --algorithm SAC --universe gym --domain HalfCheetah --task v3 --exp-name my-sac-experiment-1 --checkpoint-frequency 1000
Traceback (most recent call last):
  File "/home/noah/anaconda3/envs/softlearning/bin/softlearning", line 11, in <module>
    load_entry_point('softlearning', 'console_scripts', 'softlearning')()
  File "/home/noah/anaconda3/envs/softlearning/lib/python3.8/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/noah/anaconda3/envs/softlearning/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2853, in load_entry_point
    return ep.load()
  File "/home/noah/anaconda3/envs/softlearning/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2444, in load
    return self.resolve()
  File "/home/noah/anaconda3/envs/softlearning/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2450, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/noah/Documents/DLR/paper_comparision/softlearning/softlearning/scripts/console_scripts.py", line 26, in <module>
    from examples.instrument import (
ModuleNotFoundError: No module named 'examples.instrument'
```

**Comment by xiaxx244** [comment]
The reasons is that you might have the same environment running before. so when you run a new exp,you should either remove the previous exp's dir or change a different name for the dir saving the exp results

**Comment by Artemis-Skade** [comment]
Thank you
