### ISSUE TITLE
Error occurs while runing

### ISSUE THREAD

**Issue by Tzenthin** [rail-berkeley/softlearning#31]
When I  run the command given in README  : 

`python -m examples.development.main \
    --mode=local \
    --universe=gym \
    --domain=HalfCheetah \
    --task=v2 \
    --exp-name=my-sac-experiment-1 \
    --checkpoint-frequency=1000  # Save the checkpoint to resume training later
`

to  train the agent , however error occurs .

`pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "/home/deepglint/anaconda2/envs/softlearning/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/deepglint/anaconda2/envs/softlearning/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/deepglint/softlearning/examples/development/main.py", line 14, in <module>
    from softlearning.algorithms.utils import get_algorithm_from_variant
  File "/home/deepglint/softlearning/softlearning/algorithms/__init__.py", line 2, in <module>
    from .sac import SAC
  File "/home/deepglint/softlearning/softlearning/algorithms/sac.py", line 47
    **kwargs,
            ^
SyntaxError: invalid syntax
`
I would very appreciate it if you could give me a solution.

**Comment by hartikainen** [comment]
It seems like this might be an issue due to an incompatible python version. Installing the env from environment.yml using conda seems to run fine for me. Looking at the logs, I see that you're at least on a wrong python version (3.5 vs 3.6). Could you try upgrading your env and see if that helps? Let me know if not.

**Comment by Tzenthin** [comment]
Thank you so much for getting back to me so quickly ! With your valuable advice , the problem is solved correctly . Thank you !
