### ISSUE TITLE
No module named 'softlearning.utils'

### ISSUE THREAD

**Issue by kracon7** [rail-berkeley/softlearning#81]
I used virtualenv instead of conda on ubuntu 16.04
Ran ``` python setup.py install ``` after installing all the requirements.
When I ran the first example to train the agent I got the following error:
No module named softlearning.utils
Any idea what caused this? Thanks!

```bash
(venv) jc@jc-Precision-5510:~/research/softlearning$ softlearning run_example_local examples.development     --universe=gym     --domain=HalfCheetah     --task=v3     --exp-name=my-sac-experiment-1     --checkpoint-frequency=1000

WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

Traceback (most recent call last):
  File "/home/jc/research/softlearning/venv/bin/softlearning", line 11, in <module>
    load_entry_point('softlearning==0.0.1', 'console_scripts', 'softlearning')()
  File "/home/jc/research/softlearning/venv/lib/python3.6/site-packages/softlearning-0.0.1-py3.6.egg/softlearning/scripts/console_scripts.py", line 202, in main
  File "/home/jc/research/softlearning/venv/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/jc/research/softlearning/venv/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/jc/research/softlearning/venv/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jc/research/softlearning/venv/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jc/research/softlearning/venv/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/jc/research/softlearning/venv/lib/python3.6/site-packages/softlearning-0.0.1-py3.6.egg/softlearning/scripts/console_scripts.py", line 71, in run_example_local_cmd
  File "/home/jc/research/softlearning/venv/lib/python3.6/site-packages/softlearning-0.0.1-py3.6.egg/examples/instrument.py", line 203, in run_example_local
  File "/home/jc/research/softlearning/venv/lib/python3.6/site-packages/softlearning-0.0.1-py3.6.egg/examples/development/__init__.py", line 21, in get_parser
  File "/home/jc/research/softlearning/venv/lib/python3.6/site-packages/softlearning-0.0.1-py3.6.egg/examples/utils.py", line 8, in <module>
  File "/home/jc/research/softlearning/venv/lib/python3.6/site-packages/softlearning-0.0.1-py3.6.egg/softlearning/algorithms/__init__.py", line 1, in <module>
  File "/home/jc/research/softlearning/venv/lib/python3.6/site-packages/softlearning-0.0.1-py3.6.egg/softlearning/algorithms/sql.py", line 9, in <module>
  File "/home/jc/research/softlearning/venv/lib/python3.6/site-packages/softlearning-0.0.1-py3.6.egg/softlearning/algorithms/rl_algorithm.py", line 12, in <module>
  File "/home/jc/research/softlearning/venv/lib/python3.6/site-packages/softlearning-0.0.1-py3.6.egg/softlearning/samplers/__init__.py", line 4, in <module>
  File "/home/jc/research/softlearning/venv/lib/python3.6/site-packages/softlearning-0.0.1-py3.6.egg/softlearning/samplers/remote_sampler.py", line 10, in <module>
  File "/home/jc/research/softlearning/venv/lib/python3.6/site-packages/softlearning-0.0.1-py3.6.egg/softlearning/samplers/utils.py", line 5, in <module>
  File "/home/jc/research/softlearning/venv/lib/python3.6/site-packages/softlearning-0.0.1-py3.6.egg/softlearning/replay_pools/__init__.py", line 4, in <module>
  File "/home/jc/research/softlearning/venv/lib/python3.6/site-packages/softlearning-0.0.1-py3.6.egg/softlearning/replay_pools/trajectory_replay_pool.py", line 8, in <module>
ModuleNotFoundError: No module named 'softlearning.utils'

```

**Comment by hartikainen** [comment]
Hey, thanks for opening the issue! How did you install softlearning? Did you add `-e` to the pip install command, i.e. `pip install -e ${SOFTLEARNING_PATH}`?

**Comment by kracon7** [comment]
Hi, @hartikainen thanks for the fast response!
I first did ```pip install -r requirements.txt``` and then
 ``` python setup.py install```

**Comment by hartikainen** [comment]
Okay. Could you try doing `pip install -e ${SOFTLEARNING_PATH}` instead of `python setup.py install`? Note that you might want to uninstall the old softlearning installation:
```bash
pip uninstall softlearning
pip install -e ${SOFTLEARNING_PATH} 
# Or cd ${SOFTLEARNING_PATH} && pip install -e .
```

**Comment by kracon7** [comment]
@hartikainen  It's working now. Thank you so much.

**Comment by hartikainen** [comment]
Awesome! Happy to help!
